apiVersion: v1
kind: ConfigMap
metadata:
  name: easytravel-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: easytravel
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  MONGODB_HOST: {{ .Values.mongodb.service.name | quote }}
  MONGODB_PORT: {{ .Values.mongodb.service.port | quote }}
  MONGODB_AUTH_DB: {{ .Values.mongodb.env.authDb | quote }}
  BACKEND_SERVICE: {{ .Values.backend.service.name | quote }}
  BACKEND_PORT: {{ .Values.backend.service.port | quote }}
  FRONTEND_SERVICE: {{ .Values.frontend.service.name | quote }}
  FRONTEND_PORT: {{ .Values.frontend.service.port | quote }}
  ANGULAR_FRONTEND_SERVICE: {{ .Values.angularFrontend.service.name | quote }}
  ANGULAR_FRONTEND_PORT: {{ .Values.angularFrontend.service.port | quote }}
