apiVersion: v1
kind: Secret
metadata:
  name: easytravel-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: easytravel
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  MONGODB_USER: {{ .Values.mongodb.env.user | quote }}
  MONGODB_PASSWORD: {{ .Values.mongodb.env.password | quote }}
